### ISSUE TITLE
Support for native serialization format

### ISSUE THREAD

**Issue by andreas** [RoaringBitmap/croaring-rs#104]
It appears the native serialization format from CRoaring currently is not supported, i.e. serialization using the functions `roaring_bitmap_serialize`, `roaring_bitmap_deserialize_safe` and `roaring_bitmap_size_in_bytes`.

I'd be happy to give it a try with adding support for that, if there's interest in such a change? If so, would you prefer just adding more functions, or perhaps consolidating (de-)serialization functions with a "format" parameter?

**Comment by saulius** [comment]
Thanks for your contribution @andreas. This was resolved in https://github.com/RoaringBitmap/croaring-rs/pull/106.
