### ISSUE TITLE
croaring-rs in RoaringBitmap organisation

### ISSUE THREAD

**Issue by saulius** [RoaringBitmap/croaring-rs#109]
[As discussed](https://github.com/RoaringBitmap/croaring-rs/pull/107#issuecomment-1598441505) it makes a lot more sense for `croaring-rs` to live under [RoaringBitmap org](https://github.com/RoaringBitmap/) and be maintained by more people. The repo was transferred. Things left to do:

* [x] Change links and references in `README`, documentation
  * [x] After new release is published review if everything looks okay in https://docs.rs/croaring
* [x] Add @Dr-Emann as an owner in crates.io
* [x] Extend [`authors`](https://github.com/RoaringBitmap/croaring-rs/blob/d910cdc48f6ddd1d223a1ea5471213794ee027f4/croaring/Cargo.toml#L5)
* [x] Verify CI works: https://github.com/RoaringBitmap/croaring-rs/actions/runs/5398257035

**Comment by saulius** [comment]
@Dr-Emann , would like to add you as a crate owner on https://crates.io. Do you have an account there by any chance? Tried to use your email specified in Github, but no such user could be found.

**Comment by Dr-Emann** [comment]
I think the emails are the same, this is me: https://crates.io/users/Dr-Emann
