### ISSUE TITLE
Add std feature flag

### ISSUE THREAD

**Issue by lucascool12** [RoaringBitmap/croaring-rs#131]
Currently the croaring crate depends on the rust standard library even though it doesn't use any particular features that are only available in the std library (as far as I've seen).
Adding a std feature flag would allow this crate to be used in environments that are unable/unwilling to depend on the rust standard library, such as embedded environments.

**Comment by Dr-Emann** [comment]
At least the [TreeMap](https://docs.rs/croaring/latest/src/croaring/treemap/mod.rs.html#38-41) type is backed by a BTreeMap, and things like [`serialize`/`serialize_into`](https://docs.rs/croaring/latest/croaring/bitmap/struct.Bitmap.html#method.serialize) use Vec.

But it does seem like it wouldn't be too difficult to only require alloc, and provide a fully no-std build too.

**Comment by Dr-Emann** [comment]
Ah, one thing is our use of `std::panic::catch_unwind`, which isn't available outside of std, and there's not really a path currently to getting it in core/alloc AFAICS. I don't think there's a safe way to pass an arbitrary callback to C without it, but we could provide a `std` feature by default, and an `alloc` feature, and a completely no-std version without either.

**Comment by Dr-Emann** [comment]
Released as [croaring 2.0](https://crates.io/crates/croaring/2.0.0):
