### ISSUE TITLE
README: treemap vs bitmap64

### ISSUE THREAD

**Issue by VadeveSi** [RoaringBitmap/croaring-rs#152]
Hi,

I had a quick question about something in the README. There, it's stated that:

> For 64bit Bitmap support, checkout the [Treemap](https://docs.rs/croaring/0.4.0/croaring/treemap/struct.Treemap.html). Treemap is not API-compatible with Bitmap, yet most the functionality is overlapping.

Is there a specific reason to pick a treemap over bitmap64, or is the readme just outdated?

(Note also that the link to the treemap in docs.rs is dead)

Thanks for your response. :-)

**Comment by Dr-Emann** [comment]
I would suggest defaulting to Bitmap64. We can update the docs to more clearly point that way. I'm struggling to think of a reason to really ever prefer Treemap over Bitmap64, there are very few apis that aren't available on Bitmap64 (yet).

**Comment by VadeveSi** [comment]
Great, thx. :-)
